version: '3.8'

services:
  fastapi-app: # Service name, if have multiple services, each service should have a unique name
    build:
      context: . # Path to the Dockerfile, . means the current directory
    ports:
      - "8000:8000" # Port mapping, host:container